[2024-09-14T16:42:51.531+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-14T16:42:51.566+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_pgadmin.create_table manual__2024-09-14T16:42:48.085914+00:00 [queued]>
[2024-09-14T16:42:51.587+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_pgadmin.create_table manual__2024-09-14T16:42:48.085914+00:00 [queued]>
[2024-09-14T16:42:51.588+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-14T16:42:51.618+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create_table> on 2024-09-14 16:42:48.085914+00:00
[2024-09-14T16:42:51.630+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-14T16:42:51.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_pgadmin', 'create_table', 'manual__2024-09-14T16:42:48.085914+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/test_pgadmin_dags.py', '--cfg-path', '/tmp/tmp62ei8c3s']
[2024-09-14T16:42:51.635+0000] {standard_task_runner.py:72} INFO - Started process 887 to run task
[2024-09-14T16:42:51.635+0000] {standard_task_runner.py:105} INFO - Job 144: Subtask create_table
[2024-09-14T16:42:51.717+0000] {task_command.py:467} INFO - Running <TaskInstance: test_pgadmin.create_table manual__2024-09-14T16:42:48.085914+00:00 [running]> on host 0a5b2fe35fbd
[2024-09-14T16:42:51.877+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_pgadmin' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T16:42:48.085914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-14T16:42:48.085914+00:00'
[2024-09-14T16:42:51.879+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-14T16:42:51.916+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-14T16:42:51.918+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/***_retail_pgadmin.py']
[2024-09-14T16:42:51.940+0000] {subprocess.py:86} INFO - Output:
[2024-09-14T16:42:59.582+0000] {subprocess.py:93} INFO - [2024-09-14T16:42:59.580+0000] {base.py:84} INFO - Retrieving connection 'retail_connection'
[2024-09-14T16:42:59.608+0000] {subprocess.py:93} INFO - Successfully created table customer
[2024-09-14T16:42:59.609+0000] {subprocess.py:93} INFO - [2024-09-14T16:42:59.607+0000] {base.py:84} INFO - Retrieving connection 'retail_connection'
[2024-09-14T16:43:00.024+0000] {subprocess.py:93} INFO - Error loading data to database: duplicate key value violates unique constraint "customer_pkey"
[2024-09-14T16:43:00.026+0000] {subprocess.py:93} INFO - DETAIL:  Key (customer_id)=(12346) already exists.
[2024-09-14T16:43:00.030+0000] {subprocess.py:93} INFO - 
[2024-09-14T16:43:00.032+0000] {subprocess.py:93} INFO - [2024-09-14T16:43:00.024+0000] {base.py:84} INFO - Retrieving connection 'retail_connection'
[2024-09-14T16:43:00.037+0000] {subprocess.py:93} INFO - Successfully created table product
[2024-09-14T16:43:00.040+0000] {subprocess.py:93} INFO - [2024-09-14T16:43:00.036+0000] {base.py:84} INFO - Retrieving connection 'retail_connection'
[2024-09-14T16:43:00.051+0000] {subprocess.py:93} INFO - Successfully loaded data into product
[2024-09-14T16:43:00.829+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-14T16:43:00.882+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-14T16:43:00.884+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_pgadmin, task_id=create_table, run_id=manual__2024-09-14T16:42:48.085914+00:00, execution_date=20240914T164248, start_date=20240914T164251, end_date=20240914T164300
[2024-09-14T16:43:00.927+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-14T16:43:00.965+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-14T16:43:00.970+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
