[2024-09-15T17:57:17.901+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T17:57:17.942+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-15T17:57:17.962+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-15T17:57:17.963+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T17:57:17.998+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create_table_alchemy> on 2024-09-09 00:00:00+00:00
[2024-09-15T17:57:18.010+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1660) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-15T17:57:18.013+0000] {standard_task_runner.py:72} INFO - Started process 1661 to run task
[2024-09-15T17:57:18.013+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'create_table_alchemy', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmpbp7w5shb']
[2024-09-15T17:57:18.015+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask create_table_alchemy
[2024-09-15T17:57:18.128+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [running]> on host 6b58833345bd
[2024-09-15T17:57:18.312+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='create_table_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-09-15T17:57:18.314+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T17:57:18.343+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-15T17:57:18.345+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/test_alchemy.py']
[2024-09-15T17:57:18.367+0000] {subprocess.py:86} INFO - Output:
[2024-09-15T17:57:21.003+0000] {subprocess.py:93} INFO - /opt/***/dags/script/test_alchemy.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-15T17:57:21.005+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=self.engine, index=False, if_exists='replace')
[2024-09-15T17:57:21.006+0000] {subprocess.py:93} INFO - Error loading data to database: 'Engine' object has no attribute 'cursor'
[2024-09-15T17:57:21.180+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-15T17:57:21.243+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T17:57:21.245+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=create_table_alchemy, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20240915T175717, end_date=20240915T175721
[2024-09-15T17:57:21.301+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-15T17:57:21.344+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T17:57:21.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-16T10:17:51.993+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T10:17:52.008+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-16T10:17:52.015+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-16T10:17:52.016+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T10:17:52.027+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create_table_alchemy> on 2024-09-09 00:00:00+00:00
[2024-09-16T10:17:52.033+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=448) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T10:17:52.035+0000] {standard_task_runner.py:72} INFO - Started process 449 to run task
[2024-09-16T10:17:52.035+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'create_table_alchemy', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmp6i2k15qc']
[2024-09-16T10:17:52.036+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask create_table_alchemy
[2024-09-16T10:17:52.074+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [running]> on host 9978fde86398
[2024-09-16T10:17:52.140+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='create_table_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-09-16T10:17:52.141+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T10:17:52.152+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T10:17:52.153+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/test_alchemy.py']
[2024-09-16T10:17:52.164+0000] {subprocess.py:86} INFO - Output:
[2024-09-16T10:17:53.205+0000] {subprocess.py:93} INFO - /opt/***/dags/script/test_alchemy.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-16T10:17:53.206+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=self.engine, index=False, if_exists='replace')
[2024-09-16T10:17:53.206+0000] {subprocess.py:93} INFO - Error loading data to database: 'Engine' object has no attribute 'cursor'
[2024-09-16T10:17:53.292+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-16T10:17:53.315+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T10:17:53.316+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=create_table_alchemy, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20240916T101752, end_date=20240916T101753
[2024-09-16T10:17:53.332+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T10:17:53.351+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-16T10:17:53.352+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-16T14:47:14.949+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T14:47:14.993+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-16T14:47:15.014+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-16T14:47:15.015+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T14:47:15.047+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create_table_alchemy> on 2024-09-09 00:00:00+00:00
[2024-09-16T14:47:15.058+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=357) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T14:47:15.062+0000] {standard_task_runner.py:72} INFO - Started process 359 to run task
[2024-09-16T14:47:15.062+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'create_table_alchemy', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmpg6itn48g']
[2024-09-16T14:47:15.064+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask create_table_alchemy
[2024-09-16T14:47:15.161+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.create_table_alchemy scheduled__2024-09-09T00:00:00+00:00 [running]> on host e54c4d73c780
[2024-09-16T14:47:15.321+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='create_table_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-09-16T14:47:15.323+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T14:47:15.362+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T14:47:15.364+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/test_alchemy.py']
[2024-09-16T14:47:15.389+0000] {subprocess.py:86} INFO - Output:
[2024-09-16T14:47:18.227+0000] {subprocess.py:93} INFO - Error loading data to database: (psycopg2.OperationalError) connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: FATAL:  database "test_database" does not exist
[2024-09-16T14:47:18.229+0000] {subprocess.py:93} INFO - 
[2024-09-16T14:47:18.230+0000] {subprocess.py:93} INFO - (Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-16T14:47:18.443+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-16T14:47:18.501+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T14:47:18.503+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=create_table_alchemy, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20240916T144714, end_date=20240916T144718
[2024-09-16T14:47:18.579+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T14:47:18.624+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-16T14:47:18.629+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
